
//! Autogenerated weights for `pallet_kitties`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-20, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_kitties
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json-file=raw.json
// --output
// ./pallets/kitties/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn create_kitty() -> Weight;
	fn set_price() -> Weight;
	fn transfer() -> Weight;
	fn buy_kitty() -> Weight;
	fn breed_kitty() -> Weight;
}

/// Weight functions for `pallet_kitties`.
pub struct SubstrateWeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeightInfo<T> {
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Kitties KittyCnt (r:1 w:1)
	// Storage: Kitties Kitties (r:1 w:1)
	// Storage: Kitties KittiesOwned (r:1 w:1)
	fn create_kitty() -> Weight {
		(46_278_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Kitties Kitties (r:1 w:1)
	fn set_price() -> Weight {
		(28_272_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}

	// Storage: Kitties Kitties (r:1 w:1)
	// Storage: Kitties KittiesOwned (r:2 w:2)
	fn transfer() -> Weight {
		(25_658_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn buy_kitty() -> Weight {
		(233_000 as Weight)
	}
	// Storage: Kitties Kitties (r:3 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: Kitties KittyCnt (r:1 w:1)
	// Storage: Kitties KittiesOwned (r:1 w:1)
	fn breed_kitty() -> Weight {
		(53_706_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}

impl WeightInfo for () {
	fn create_kitty() -> Weight {
		(46_593_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: Kitties Kitties (r:1 w:1)
	fn set_price() -> Weight {
		(22_523_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	// Storage: Kitties Kitties (r:1 w:1)
	// Storage: Kitties KittiesOwned (r:2 w:2)
	fn transfer() -> Weight {
		(25_658_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn buy_kitty() -> Weight {
		(233_000 as Weight)
	}
	// Storage: Kitties Kitties (r:3 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: Kitties KittyCnt (r:1 w:1)
	// Storage: Kitties KittiesOwned (r:1 w:1)
	fn breed_kitty() -> Weight {
		(53_706_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(8 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
}